using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using Pacioli.Lib.Identity.Models;
using Pacioli.WebApi.Models;
using Pacioli.WebApi.Services;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Pacioli.WebApi.Controllers
{
    [Route("api/[controller]"), ApiController]
    public class UserController : ControllerBase
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IConfiguration _configuration;
        private readonly AccessTokenGenerator _accessTokenGenerator;

        public UserController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager, 
            IConfiguration configuration, AccessTokenGenerator accessTokenGenerator)
        {
            _configuration = configuration;
            _roleManager = roleManager;
            _accessTokenGenerator = accessTokenGenerator;
            _userManager = userManager;
        }

        //TODO : Registration should require a special one-time permission token generated by staff.
        [HttpPost("register")]
        public async Task<IActionResult> RegisterAsync(RegisterModel model)
        {
            if (ModelState.IsValid is false) 
                return BadRequest();

            bool userExists = await _userManager.FindByEmailAsync(model.Email) is not null ||
                              await _userManager.FindByNameAsync(model.Username) is not null;
            if (userExists)
                return Conflict();

            var user = new User
            {
                UserName = model.Username,
                Email = model.Email,
                SecurityStamp = Guid.NewGuid().ToString()
            };

            var userCreationResult = await _userManager.CreateAsync(user, model.Password);
            if (userCreationResult.Succeeded is false)
                return StatusCode(StatusCodes.Status500InternalServerError);

            //TODO : Move to role initialization
            await EnsureRolesExistAsync(model.Roles);

            var roleAdditionResult = await _userManager.AddToRolesAsync(user, model.Roles);
            if (roleAdditionResult.Succeeded is false)
                return StatusCode(StatusCodes.Status500InternalServerError);

            //TODO : Replace with Created(userLookupUri, user.Id)
            return Ok();
        }

        [HttpPost("login")]
        public async Task<IActionResult> LoginAsync(LoginModel model)
        {
            if (ModelState.IsValid is false) 
                return BadRequest();

            var user = await _userManager.FindByEmailAsync(model.Email);
            if (user is null || await _userManager.CheckPasswordAsync(user, model.Password) is false)
                return Unauthorized();

            var authClaims = await GetUserAuthClaimsAsync(user);
            var authSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT:Secret"]));

            string token = _accessTokenGenerator.GenerateToken(_configuration["JWT:ValidIssuer"],
                _configuration["JWT:ValidAudience"], authClaims, authSigningKey);

            return Ok(new TokenGrantModel { Token = token });
        }

        private async Task EnsureRolesExistAsync(IEnumerable<string> roleNames)
        {
            foreach (string roleName in roleNames)
                if (await _roleManager.RoleExistsAsync(roleName) is false)
                    await _roleManager.CreateAsync(new IdentityRole(roleName));
        }

        private async Task<List<Claim>> GetUserAuthClaimsAsync(User user)
        {
            var userRoles = await _userManager.GetRolesAsync(user);

            var authClaims = new List<Claim>
            {
                new Claim("id", user.Id),
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
            };
            authClaims.AddRange(userRoles.Select(userRole => new Claim(ClaimTypes.Role, userRole)));
            
            return authClaims;
        }
    }
}
